#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# update terminal text colors and font
xrdb -merge ~/.Xresources

# exec gnome-session
# exec startkde
# exec dbus-launch startxfce4
# ...or the Window Manager of your choice

#exec i3 -V >> ~/.i3/log 2>&1
exec i3

# for transparency and fancy effects in i3
#exec xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &

