local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, { desc = 'find files' })
vim.keymap.set('n', '<leader>pg', builtin.live_grep, { desc = 'grep in files' })
vim.keymap.set('n', '<leader>pp', builtin.git_files, { desc = 'find git files' })
vim.keymap.set('n', '<leader>ph', builtin.help_tags, { desc = 'grep in vim help' })
