-- Customize Treesitter

---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = {
      enable = true,
    },
    textobjects = {
      select = {
          enable = true,
          lookahead = true,
          keymaps = {
              ["af"] = { query = "@function.outer", desc = "Select outer part of function" },
              ["if"] = { query = "@function.inner", desc = "Select inner part of function" },
              ["ac"] = { query = "@class.outer"   , desc = "Select outer part of class" },
              ["ic"] = { query = "@class.inner"   , desc = "Select inner part of class" },
              ["as"] = { query = "@local.scope", query_group = "locals", desc = "Select language scope" },
          },
      },
    },
    auto_install = true,
    ensure_installed = {
      "lua",
      "vim",
      "vimdoc",
      "query",
      "c",
      "cpp",
      "cmake",
      "make",
      "meson",
      "rust",
      "python",
      "go",
      "java",
      "kotlin",
      "perl",
      "php",
      "swift",
      "typescript",
      "zig",
      "llvm",
      "bash",
      "fish",
      "powershell",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "ssh_config",
      "nix",
      "passwd",
      "udev",
      "strace",
      "sway",
      "tmux",
      "todotxt",
      "comment",
      "toml",
      "yaml",
      "ini",
      "json",
      "proto",
      "csv",
      "xml",
      "regex",
      "dockerfile",
      "markdown",
      "mermaid",
      "html",
      "css",
      "sql",
      "gpg",
      "groovy",
      "printf",
    },
  },
}
