theme = "onedarker_transparent"

[editor]
bufferline = "multiple" # show open buffers only when multiple are open
cursorline = false # Highlight all lines with a cursor
line-number = "relative"
scroll-lines = 3 # mouse wheel scrolling
mouse = false
rulers = [100] # column rulers
true-color = true # Force the theme to show colors

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
nbsp = "all"
nnbsp = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "▸"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
    "mode", "spinner", "separator",
    "version-control", "separator",
    "file-name", "file-modification-indicator", "read-only-indicator", "separator"
]
center = ["diagnostics"]
right = [
    "separator", "file-type", "file-encoding",
    "separator", "position",
    "separator", "position-percentage" ,"total-line-numbers"
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"



[keys.normal]
# use q to go back one word
g = { a = "code_action" }
q = "move_prev_word_start"
Q = "move_prev_long_word_start"

# use Tab to jump
tab = "extend_to_word"

# remap x to have same behaviour in empty lines
x = ["extend_to_line_bounds", "select_mode"]

# use Shift+X to shrink line selection
X = ["extend_line_up", "extend_to_line_bounds"]

# move faster with ctrl
C-up = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]
C-down = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
C-left = "move_prev_word_start"
C-right = "move_next_word_start"
C-k = "page_cursor_half_up"
C-j = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
C-h = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]
C-l = "move_next_word_start"

# move lines with shift
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-left = "unindent"
S-right = "indent"

# search for word under cursor
# TODO replace this with something better
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]

[keys.normal.space]
# toggle whitespaces
# space = ":toggle whitespace.render all none"
space = ":toggle whitespace.render"

# toggle mouse
m = ":toggle-option mouse"

# global search for word under cursor
# TODO replace this with something better
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection", "global_search"]

[keys.select]
# use q to go back one word
q = "extend_prev_word_start"
Q = "extend_prev_long_word_start"

# use Tab to jump
tab = "extend_to_word"

# remap x to have same behaviour in empty lines
x = ["extend_line"]

# use Shift+X to shrink line selection
X = ["extend_line_up", "extend_to_line_bounds"]

# yank-less delete/change
d = "delete_selection_noyank"
c = "change_selection_noyank"

# move faster with ctrl
C-down = ["extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down"]
C-up = ["extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up"]
C-left = "extend_prev_word_start"
C-right = "extend_next_word_start"
C-j = ["extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down"]
C-k = ["extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up"]
C-h = "extend_prev_word_start"
C-l = "extend_next_word_start"

# move lines with shift
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-left = "unindent"
S-right = "indent"

[keys.insert]
# use q to go back one word
q = "move_prev_word_start"
Q = "move_prev_long_word_start"

# move faster with ctrl
C-up = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]
C-down = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
C-left = "move_prev_word_start"
C-right = "move_next_word_start"

# move lines with shift
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-left = "unindent"
S-right = "indent"

C-space = "completion"



# TODO
# toggle gutters (space 1)
# toggle tab (space tab)
# toggle spaces (space space?)
# clear highlighting (keep_primary_selection, collapse_selection -> space space?)
# gb / gf - go back / go forward
# space s - replace word under cursor? (leader s taken :( )
# maybe remap remove_primary_selection
# _ as word separator
# map jump_forward / jump_backward
# remap save_selection?
# pick better theme for rust
# check out config.like.nvim



# useful links
# https://kapeli.com/cheat_sheets/Helix.docset/Contents/Resources/Documents/index
# https://github.com/helix-editor/helix/wiki/Migrating-from-Vim
