theme = "transparent_github_dark"

[editor]
bufferline = "multiple" # show open buffers only when multiple are open
cursorline = false # Highlight all lines with a cursor
line-number = "relative"
scroll-lines = 3 # mouse wheel scrolling
mouse = false
rulers = [100] # column rulers
true-color = true # Force the theme to show colors

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
nbsp = "all"
nnbsp = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "▸"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
    "mode", "spinner", "separator",
    "version-control", "separator",
    "file-name", "file-modification-indicator", "read-only-indicator", "separator"
]
center = ["diagnostics"]
right = [
    "separator", "file-type", "file-encoding",
    "separator", "position",
    "separator", "position-percentage" ,"total-line-numbers"
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"



[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

# use q to go back one word
q = "move_prev_word_start"
Q = "move_prev_long_word_start"

# use V to reduce cursors
V = "remove_primary_selection"

# use Tab to jump
tab = "goto_word"

# remap x to have same behaviour in empty lines
x = ["extend_to_line_bounds", "select_mode"]

# use Shift+X to shrink line selection
X = ["extend_line_up", "extend_to_line_bounds"]

# yank-less delete/change
d = "delete_selection_noyank"
c = "change_selection_noyank"

# move faster with ctrl
C-up = "goto_prev_paragraph"
C-down = "goto_next_paragraph"
C-left = "move_prev_word_start"
C-right = "move_next_word_start"
C-k = "goto_prev_paragraph"
C-j ="goto_next_paragraph"

C-h = "move_prev_word_start"
C-l = "move_next_word_start"

# move lines with shift
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-left = "unindent"
S-right = "indent"

# search for word under cursor
"*" = ["move_next_word_start", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]

[keys.normal.space]
# toggle mouse
m = ":toggle-option mouse"

# global search for word under cursor
# TODO replace this with something better
"*" = ["move_next_word_start", "move_prev_word_start", "move_next_word_end", "search_selection", "global_search"]

# TODO search and replace word under cursor
# R = ["move_next_word_start", "move_prev_word_start", "move_next_word_end", "search_selection", "select_all", "select_regex"]

[keys.normal."ö"]
"d" = "goto_prev_diag"
"D" = "goto_first_diag"
"g" = "goto_prev_change"
"G" = "goto_first_change"
"f" = "goto_prev_function"
"t" = "goto_prev_class"
"a" = "goto_prev_parameter"
"c" = "goto_prev_comment"
# "e" = "goto_prev_entry"
"T" = "goto_prev_test"
"p" = "goto_prev_paragraph"
"space" = "add_newline_above"

[keys.normal."ä"]
"d" = "goto_next_diag"
"D" = "goto_last_diag"
"g" = "goto_next_change"
"G" = "goto_last_change"
"f" = "goto_next_function"
"t" = "goto_next_class"
"a" = "goto_next_parameter"
"c" = "goto_next_comment"
# "e" = "goto_next_entry"
"T" = "goto_next_test"
"p" = "goto_next_paragraph"
"space" = "add_newline_below"

[keys.select]
# reset selection/cursors when exiting select
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

# use q to go back one word
q = "extend_prev_word_start"
Q = "extend_prev_long_word_start"

# use V to reduce cursors
V = "remove_primary_selection"

# use Tab to jump
tab = "extend_to_word"

# remap x to have same behaviour in empty lines
x = ["extend_line"]

# use Shift+X to shrink line selection
X = ["extend_line_up", "extend_to_line_bounds"]

# yank-less delete/change
D = "delete_selection_noyank"
c = "change_selection_noyank"

# move faster with ctrl
C-up = "goto_prev_paragraph"
C-down = "goto_next_paragraph"
C-left = "extend_prev_word_start"
C-right = "extend_next_word_start"
C-k = "goto_prev_paragraph"
C-j = "goto_next_paragraph"
C-h = "extend_prev_word_start"
C-l = "extend_next_word_start"

# move lines with shift
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-left = "unindent"
S-right = "indent"

[keys.normal.g]
a = "code_action"
k = "goto_prev_paragraph"
j = "goto_next_paragraph"
up = "goto_prev_paragraph"
down = "goto_next_paragraph"

[keys.normal.n]
n = "search_next"

[keys.insert]
# move faster with ctrl
C-up = "goto_prev_paragraph"
C-down = "goto_next_paragraph"
C-left = "move_prev_word_start"
C-right = "move_next_word_start"

# move lines with shift
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-left = "unindent"
S-right = "indent"

# completion
C-space = "completion"



# TODO
# toggle whitespaces (":toggle whitespace.render all none")
# toggle gutters (space 1)
# toggle tab (space tab)
# _ as word separator?
# whichwrap: https://github.com/helix-editor/helix/issues/768



# useful links
# https://kapeli.com/cheat_sheets/Helix.docset/Contents/Resources/Documents/index
# https://github.com/helix-editor/helix/wiki/Migrating-from-Vim
# https://github.com/LGUG2Z/helix-vim
