alias ls='exa'
alias grep='grep --color=always'
alias agl='ag --pager="less -R"'
alias dmesg='dmesg --color=always -H'
alias tree='tree -C'
alias less='less -R'
alias beep='play /usr/share/sounds/freedesktop/stereo/bell.oga > /dev/null 2>&1'
alias vim='nvim'
alias printconfig='system-config-printer'
alias print='lpr'
